name: Make Duolingo words

on:
  workflow_dispatch:

env:
  # uncomment these if you are using azure
  #API_TYPE: ${{ secrets.API_TYPE }}
  # OPENAI_API_BASE: ${{ secrets.OPENAI_API_BASE }}
  # OPENAI_ENGINE: ${{ secrets.OPENAI_ENGINE }}
  # OPENAI_API_VERSION: ${{ secrets.OPENAI_API_VERSION }}
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  EDGE_GPT_COOKIE: ${{ secrets.EDGE_GPT_COOKIE }}
  LATEST_WORDS_NUMBER: 20

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: agu
        run: sudo apt-get update
      - name: Setup ffmpeg for differnt platforms
        uses: FedericoCarboni/setup-ffmpeg@main
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Send new words
        run: |
          python duolingo.py ${{ secrets.DUOLINGO_USERNAME }} ${{ secrets.DUOLINGO_JWT }}  --tele_token ${{ secrets.TELE_TOKEN }} --tele_chat_id ${{ secrets.TELE_CHAT_ID }} --latest_number ${{ env.LATEST_WORDS_NUMBER }}
